const BASE_URL="http://localhost:8080"
export const REGISTER_AMBULANCE_SERVICE = BASE_URL+"/api/v1/service/register"
export const GET_AMBULANCE_SERVICES = BASE_URL+"/api/v1/service/getAll"
export const GET_AMBULANCE_SERVICE = BASE_URL+"/api/v1/service/getService"
export const EDIT_AMBULANCE_SERVICE = BASE_URL+"/api/v1/service/edit"
export const DELETE_AMBULANCE_SERVICE = BASE_URL+"/api/v1/service/delete"
