export const BASE_URL="http://localhost:8080"
export const REGISTER_AMBULANCE_SERVICE = BASE_URL+"/api/v1/serviceProvider/register"
export const GET_AMBULANCE_SERVICES = BASE_URL+"/api/v1/serviceProvider/getAll"
export const GET_AMBULANCE_SERVICE = BASE_URL+"/api/v1/serviceProvider/getServiceProvider"
export const EDIT_AMBULANCE_SERVICE = BASE_URL+"/api/v1/serviceProvider/edit"
export const DELETE_AMBULANCE_SERVICE = BASE_URL+"/api/v1/serviceProvider/delete"
